### ISSUE TITLE
can't install on archlinux

### ISSUE THREAD

**Issue by dragonauta** [netvirt/netvirt#21]
Hi, I'm using instructions as per dynvpn.com site to install netvirt-agent-cli on archlinux
But it fails and can't find what I'm missing. 
I see i586-mingw32msvc-strip command not found, but there's no such package on arch nor aur
If you can't point me in the right direction, I will appreciate it. 
Thanks

==> Making package: netvirt-agent-git 0.6.r20.g3798298-3798298 (Sun Sep  6 00:00:31 ART 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating netvirt-agent-git git repo...
Fetching origin
==> Validating source files with md5sums...
    netvirt-agent-git ... Skipped
==> Extracting sources...
  -> Creating working copy of netvirt git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
fatal: No names found, cannot describe anything.
==> Starting prepare()...
~/git/netvirt-agent-git/src/netvirt-agent-git/udt4 ~/git/netvirt-agent-git/src/netvirt-agent-git
~/git/netvirt-agent-git/src/netvirt-agent-git
~/git/netvirt-agent-git/src/netvirt-agent-git/libconfig ~/git/netvirt-agent-git/src/netvirt-agent-git
~/git/netvirt-agent-git/src/netvirt-agent-git
~/git/netvirt-agent-git/src/netvirt-agent-git/tapcfg ~/git/netvirt-agent-git/src/netvirt-agent-git
build/daemon/serversock.c: In function 'serversock_tcp':
build/daemon/serversock.c:57:24: warning: variable 'caddr_size' set but not used [-Wunused-but-set-variable]
  socklen_t saddr_size, caddr_size;
                        ^
build/daemon/serversock.c:56:19: warning: variable 'caddr' set but not used [-Wunused-but-set-variable]
  struct sockaddr *caddr;
                   ^
/bin/ld: unrecognized option '--out-implib'
/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
scons: *** [build/tapcfg.dll] Error 1
mv: cannot stat 'build/tapcfg.dll': No such file or directory
./buildall.sh: line 8: i586-mingw32msvc-strip: command not found
/bin/ld: unrecognized option '--out-implib'
/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
scons: *** [build/tapcfg.dll] Error 1
mv: cannot stat 'build/tapcfg.dll': No such file or directory
./buildall.sh: line 12: amd64-mingw32msvc-strip: command not found
build/daemon/serversock.c: In function 'serversock_tcp':
build/daemon/serversock.c:57:24: warning: variable 'caddr_size' set but not used [-Wunused-but-set-variable]
  socklen_t saddr_size, caddr_size;
                        ^
build/daemon/serversock.c:56:19: warning: variable 'caddr' set but not used [-Wunused-but-set-variable]
  struct sockaddr *caddr;
                   ^
build/daemon/client.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
 /**
 ^
scons: *** [build/daemon/client.o] Error 1
mv: cannot stat 'build/libtapcfg.so': No such file or directory
strip: 'release/libtapcfg64.so': No such file
build/daemon/serversock.c: In function 'serversock_tcp':
build/daemon/serversock.c:57:24: warning: variable 'caddr_size' set but not used [-Wunused-but-set-variable]
  socklen_t saddr_size, caddr_size;
                        ^
build/daemon/serversock.c:56:19: warning: variable 'caddr' set but not used [-Wunused-but-set-variable]
  struct sockaddr *caddr;
                   ^
mv: cannot stat 'build/TAPNet.dll': No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by nicboul** [comment]
mmm, let me have a look and I'll get back to you !

**Comment by mathieujobin** [comment]
What? mingw32msvc? This is Ming a C compiler for Win32 Microsoft VC?!? How can you see this on ArchLinux? Something is wrong around OS detection...

You are building with yaourt -S netvirt-agent-git 

What is your hardware?

**Comment by mathieujobin** [comment]
I am now sure what instruction you found. But there is netvirt package in AUR


https://aur4.archlinux.org/packages/netvirt-agent-git/

**Comment by dragonauta** [comment]
Hi mathieujobin, here're my instructions:
$ git clone https://aur4.archlinux.org/netvirt-agent-git/
$ cd netvirt-agent-git
$ makepkg -si

don't know what happened. 
What is doing Ming inside a *nix shell script (buildall.sh)??

I'm on arch on an old Toshiba NB100 intel Atom+2GB Ram (x86)
$ uname -a
Linux koi 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 09:07:24 CEST 2015 i686 GNU/Linux

**Comment by mathieujobin** [comment]
thanks for the reply with the extra info... 

hmm, good question. buildall.sh is part of Tapcfg

@nicboul any idea why tapcfg needs to do a buildall include .dll files instead of targeting the required platform?

https://github.com/netvirt/tapcfg/blob/a94f2a40fad5b4beac5a6f4ed7dbef7cb38138a1/buildall.sh

**Comment by mathieujobin** [comment]
funny part is that i don't have the executable on my archlinux either.
```
$ i586-mingw32msvc-strip
bash: i586-mingw32msvc-strip: command not found
$ uname -a
Linux hz550 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux
```

@nicboul any clue ? I'm afraid this has nothing to do with the packaging for ArchLinux but something else? Could it be because he has an Atom ?

**Comment by nicboul** [comment]
it is strange, it shouldn't matter -- buildall.sh is suppose to try to build for all platform, and only the valid valid file will be created -- maybe all of them just failed

@mathieujobin can you paste the log output when you build the package please, so we have a working example to compare, thank you

**Comment by mathieujobin** [comment]
I just realized that, just now. it follow through, so that missing compiler for windows does not matter.
as you said, all 4 are failing so that's why.
I am trying to understand why the 32 bit failed, we would need to test with a 32bit system.

suddenly wonder if that 2036 bug still exist in Linux 32 bit ;) well, we got yet another 21 years

**Comment by nicboul** [comment]
@dragonauta could you paste the complete log output here please, thank you

**Comment by mathieujobin** [comment]
turns out, this is failing for me as well.
same error.
they (`makepkg`) must have enforced the return value of prepare()
I am trying something...

**Comment by mathieujobin** [comment]
fix coming up

**Comment by nicboul** [comment]
you might try ./buildall.sh || true

what will force a positive exit code

**Comment by mathieujobin** [comment]
yop, that's what I picked up from the .travis.yml file ;) 

package is updated https://aur.archlinux.org/packages/netvirt-agent-git/

@dragonauta please try again

**Comment by nicboul** [comment]
:+1:

**Comment by mathieujobin** [comment]
its funny because AUR4 makes sure every commits has a valid PKGBUILD file, which I thought was overkill since you might want to have some de history inside your repo. And the reason given to me was to be able to rollback. and they are making changes so that rollback is no longer possible. well, nothing is perfect.

**Comment by nicboul** [comment]
@mathieujobin thank you !
now I'm eager to see if it will work for @dragonauta  :-)

**Comment by mathieujobin** [comment]
@nicboul you can close the issue, @dragonauta can reopen if he still has a problem.

**Comment by nicboul** [comment]
@mathieujobin true that !

**Comment by dragonauta** [comment]
Wow! that was fast!
It's working now.
Thanks both @nicboul @mathieujobin !

**Comment by mathieujobin** [comment]
we are missing a postinstall item if you need to run netvirt as a user


   sudo chmod 666 /dev/net/tun
   sudo setcap cap_net_bind_service,cap_net_admin=ep /usr/bin/netvirt-agent

**Comment by mathieujobin** [comment]
@dragonauta look at my previous comment

**Comment by dragonauta** [comment]
@mathieujobin excellent. I was running it as sudo, as per it needs to create a tun dev.
thanks.
Tested and working

**Comment by madduci** [comment]
Hi, the PKGBUILD contains errors:

```
==> ERROR: license should be an array
==> ERROR: source should be an array
==> ERROR: url should not be an array
```
