### ISSUE TITLE
Debian 8

### ISSUE THREAD

**Issue by bertenvdb** [netvirt/netvirt#22]
No debian 8? Any plans for this?

**Comment by fenrelot** [comment]
use https://github.com/netvirt/netvirt/blob/master/build_farm/build-debian.sh
to build .deb package for your Ubuntu 16.04 (worked for me)

should work for debian 8 aswell

**Comment by nicboul** [comment]
https://github.com/netvirt/netvirt/commit/b11b2047ea4a3842468b710dc3d1b58b1ddc68b8

Now added the instruction to get the Debian 8 package
