### ISSUE TITLE
Support Ubuntu16.04？

### ISSUE THREAD

**Issue by stonycat** [netvirt/netvirt#30]

**Comment by fenrelot** [comment]
use https://github.com/netvirt/netvirt/blob/master/build_farm/build-debian.sh
to build .deb package for your Ubuntu 16.04 (worked for me)

**Comment by craysiii** [comment]
I just tried what @fenrelot suggested, however it fails to build. I get an error:

`
[ 97%] Linking CXX executable netvirt-agent
/usr/bin/ld: cannot find -ltapcfg
`

Am i missing some packages? Or maybe I need to set up an interface?

**Comment by nicboul** [comment]
netvirt-agent2 support the latest version of Ubuntu
