### ISSUE TITLE
Debian 9 support

### ISSUE THREAD

**Issue by Juniorsnet** [netvirt/netvirt#33]
I tried to compile with build-farm in Debian 9 but I got the following error:

 82%] Building C object libnvcore/src/CMakeFiles/nvcore.dir/crypto.c.o
/netvirt/libnvcore/src/crypto.c: In function ‘get_dh_1024’:
/netvirt/libnvcore/src/crypto.c:62:4: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
  dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
    ^~
/netvirt/libnvcore/src/crypto.c: In function ‘krypt_set_renegotiate’:
/netvirt/libnvcore/src/crypto.c:179:13: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
   kconn->ssl->state = SSL_ST_ACCEPT;

I tried install the deb package but in debian 9 not have libssl1.0

**Comment by nicboul** [comment]
netvirt-agent2 now support Debian9, see https://doc.dynvpn.com
