### ISSUE TITLE
Correction on Install Document

### ISSUE THREAD

**Issue by SteveD70** [netvirt/netvirt#34]
repository is mistakenly listed in install document as:
add-apt-repository "deb http://download.opensuse.org/repositories/home:/netvirt/xUbuntu_14.10 ./"

when the correct working location is:
add-apt-repository "deb http://download.opensuse.org/repositories/home:/netvirt/xUbuntu_14.04 ./"

**Comment by nicboul** [comment]
netvirt-agent2 doesn't use opensuse build anymore
